name: Update copyright year(s) in license file

on: workflow_dispatch

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branchName: license/{{currentYear}}
          commitTitle: Update license copyright year
          commitBody: Let's keep legal happy.
          prTitle: Update my license
          prBody: It's that time of the year, let's update the license.
          assignees: MyUser, SomeMaintainer
          labels: documentation, legal
